import {StyleSheet} from 'react-native';
import {COLORS} from '../../../constants/colors/Color';
import {FONTS} from '../../../constants/fonts/Font';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    alignItems: 'center',
    justifyContent: 'center',
  },

  inputView: {
    borderRadius: 20,
    width: 331,
    height: 58,
    marginBottom: 40,
  },
  TextInput: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BG,
    color: COLORS.BLACK,
  },
  lable: {
    fontFamily: FONTS.REGULAR,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '500',
    color: COLORS.LABLE,
  },
  forgot_button: {
    fontFamily: FONTS.REGULAR,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '500',
    color: COLORS.LABLE,
    top: 20,
  },
  loginBtn: {
    width: 327,
    borderRadius: 25,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 150,
    backgroundColor: 'transparent',
  },
  loginBtnText: {
    color: COLORS.WHITE,
    fontSize: 16,
    lineHeight: 16,
    fontWeight: '700',
    fontFamily: FONTS.REGULAR,
  },
  main: {
    width: 160,
    height: 18,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 18,
    color: COLORS.LABLE,
    marginBottom: 5,
  },
  des: {
    width: 293,
    height: 40,
    textAlign: 'center',
    fontWeight: '300',
    lineHeight: 20,
    fontSize: 14,
    color: COLORS.LIGHT,
    fontFamily: FONTS.REGULAR,
  },
  img: {
    height: 48,
    width: 48,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 15,
    justifyContent: 'center',
  },
  bellowGoogle: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 332,
    height: 14,
    marginBottom: 30,
  },
  view2nd: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: COLORS.BG,
  },
  orLeft: {
    color: COLORS.LIGHT,
    fontWeight: '900',
    fontSize: 14,
    lineHeight: 14,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  orRight: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: COLORS.BG,
  },
});
