import {StyleSheet} from 'react-native';
import {FONTS} from '../../../constants/fonts/Font';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:
      'linear-gradient(271.23deg, #43116A 36.61%, #68E1FD 106.23%)',
    alignItems: 'center',
    justifyContent: 'center',
    height: 1040,
  },
  lable: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 14,
    fontWeight: '500',
    color: '#3D4A7A',
  },
  forgot_button: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 14,
    fontWeight: '500',
    color: '#3D4A7A',
    top: 20,
    marginBottom: 70,
  },

  loginBtnText: {
    width: 327,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    borderRadius: 25,
    height: 48,
    lineHeight: 16,
    fontWeight: '700',
    fontFamily: 'Poppins',
    color: '#FFFFFF',
    backgroundColor: 'rgba(255, 255, 255, 0.37)',
    marginBottom: 40,
  },
  mainHeading: {
    marginTop: 20,
    marginLeft: 25,
    width: 338,
    flex: 1,
    height: 312,
    fontWeight: '700',
    fontSize: 68,
    lineHeight: 78,
    color: 'rgba(255, 255, 255, 1)',
  },
  description: {
    width: 293,
    height: 52,
    textAlign: 'center',
    fontWeight: '300',
    lineHeight: 26,
    fontSize: 16,
    color: '#797C7B',
    fontFamily: FONTS.EXBOLD,
    marginBottom: 10,
  },
  img: {
    height: 48,
    width: 48,
    marginTop: 20,
    marginBottom: 30,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: '#797C7B',
    borderRadius: 25,
  },
  orMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 332,
    height: 14,
    marginBottom: 30,
  },
  orText: {
    color: 'white',
    fontWeight: '900',
    fontSize: 14,
    lineHeight: 14,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    fontFamily: FONTS.BOLD,
  },
  orFirstView: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: '#CDD1D0',
  },
  orSecondView: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: '#CDD1D0',
  },
  login: {
    color: '#FFFFFF',
  },
});
