import {StyleSheet} from 'react-native';
import {FONTS} from '../../../constants/fonts/Font';
import {COLORS} from '../../../constants/colors/Color';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 1040,
  },
  forgot_button: {
    fontFamily: FONTS.LIGHT,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
    color: COLORS.WHITE,
    top: 20,
    marginBottom: 70,
  },

  loginBtnText: {
    width: 327,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    borderRadius: 25,
    height: 48,
    lineHeight: 16,
    fontWeight: '700',
    fontFamily: FONTS.REGULAR,
    color: COLORS.WHITE,
    backgroundColor: 'rgba(255, 255, 255, 0.37)',
    marginBottom: 40,
  },
  mainHeading: {
    marginTop: 20,
    marginLeft: 25,
    width: 338,
    fontFamily: FONTS.LIGHT,
    flex: 1,
    height: 312,
    fontWeight: '400',
    fontSize: 68,
    lineHeight: 78,
    color: 'rgba(255, 255, 255, 1)',
  },
  description: {
    width: 293,
    height: 52,
    textAlign: 'center',
    fontWeight: '300',
    lineHeight: 26,
    fontSize: 16,
    color: COLORS.LIGHT,
    fontFamily: FONTS.LIGHT,
    marginBottom: 10,
  },
  img: {
    height: 48,
    width: 48,
    marginTop: 20,
    marginBottom: 30,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.LIGHT,
    borderRadius: 25,
  },
  orMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 332,
    height: 14,
    marginBottom: 30,
  },
  orText: {
    color: COLORS.WHITE,
    fontWeight: '900',
    fontSize: 14,
    lineHeight: 14,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    fontFamily: FONTS.BOLD,
  },
  orFirstView: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: COLORS.BG,
  },
  orSecondView: {
    flex: 1,
    width: 132,
    height: 1,
    backgroundColor: COLORS.BG,
  },
  login: {
    color: COLORS.WHITE,
    fontFamily: FONTS.BOLD,
    fontWeight: '700',
  },
});
